/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SeersLeagueV2 {
  export type MatchStruct = {
    id: BigNumberish;
    startTime: BigNumberish;
    homeScore: BigNumberish;
    awayScore: BigNumberish;
    isRecorded: boolean;
    exists: boolean;
    recordedAt: BigNumberish;
  };

  export type MatchStructOutput = [
    id: bigint,
    startTime: bigint,
    homeScore: bigint,
    awayScore: bigint,
    isRecorded: boolean,
    exists: boolean,
    recordedAt: bigint
  ] & {
    id: bigint;
    startTime: bigint;
    homeScore: bigint;
    awayScore: bigint;
    isRecorded: boolean;
    exists: boolean;
    recordedAt: bigint;
  };

  export type PredictionStruct = {
    matchId: BigNumberish;
    outcome: BigNumberish;
    timestamp: BigNumberish;
    isProcessed: boolean;
  };

  export type PredictionStructOutput = [
    matchId: bigint,
    outcome: bigint,
    timestamp: bigint,
    isProcessed: boolean
  ] & {
    matchId: bigint;
    outcome: bigint;
    timestamp: bigint;
    isProcessed: boolean;
  };

  export type UserStatsStruct = {
    correctPredictions: BigNumberish;
    totalPredictions: BigNumberish;
    freePredictionsUsed: BigNumberish;
    currentStreak: BigNumberish;
    longestStreak: BigNumberish;
    lastPredictionTime: BigNumberish;
    totalFeesPaid: BigNumberish;
  };

  export type UserStatsStructOutput = [
    correctPredictions: bigint,
    totalPredictions: bigint,
    freePredictionsUsed: bigint,
    currentStreak: bigint,
    longestStreak: bigint,
    lastPredictionTime: bigint,
    totalFeesPaid: bigint
  ] & {
    correctPredictions: bigint;
    totalPredictions: bigint;
    freePredictionsUsed: bigint;
    currentStreak: bigint;
    longestStreak: bigint;
    lastPredictionTime: bigint;
    totalFeesPaid: bigint;
  };
}

export interface SeersLeagueV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_MATCHES_THRESHOLD"
      | "PREDICTION_DEADLINE"
      | "PREDICTION_FEE"
      | "TOTAL_FREE_PREDICTIONS"
      | "UPDATE_COOLDOWN"
      | "USDC"
      | "VERSION"
      | "batchRecordResults"
      | "getContractInfo"
      | "getMatch"
      | "getMatchStatistics"
      | "getUpcomingMatches"
      | "getUserPrediction"
      | "getUserStats"
      | "lastLeaderboardUpdate"
      | "lastMatchUpdate"
      | "matches"
      | "owner"
      | "pause"
      | "paused"
      | "predictions"
      | "registerMatches"
      | "renounceOwnership"
      | "setTreasury"
      | "submitPredictions"
      | "totalMatches"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateLeaderboard"
      | "updateMatchResult"
      | "userPredictionHistory"
      | "userStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoMatchUpdate"
      | "LeaderboardUpdated"
      | "MatchRegistered"
      | "MatchResultUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PredictionsSubmitted"
      | "ResultRecorded"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_MATCHES_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PREDICTION_DEADLINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PREDICTION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FREE_PREDICTIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPDATE_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchRecordResults",
    values: [AddressLike[], BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUpcomingMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPrediction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastLeaderboardUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastMatchUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMatches",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPredictions",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "totalMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateMatchResult",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPredictionHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStats",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_MATCHES_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PREDICTION_DEADLINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PREDICTION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FREE_PREDICTIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPDATE_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchRecordResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMatchStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpcomingMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastLeaderboardUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMatchUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPredictionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStats", data: BytesLike): Result;
}

export namespace AutoMatchUpdateEvent {
  export type InputTuple = [added: BigNumberish, total: BigNumberish];
  export type OutputTuple = [added: bigint, total: bigint];
  export interface OutputObject {
    added: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [timestamp: BigNumberish, totalUsers: BigNumberish];
  export type OutputTuple = [timestamp: bigint, totalUsers: bigint];
  export interface OutputObject {
    timestamp: bigint;
    totalUsers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchRegisteredEvent {
  export type InputTuple = [matchId: BigNumberish, startTime: BigNumberish];
  export type OutputTuple = [matchId: bigint, startTime: bigint];
  export interface OutputObject {
    matchId: bigint;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResultUpdatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    homeScore: BigNumberish,
    awayScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    homeScore: bigint,
    awayScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    homeScore: bigint;
    awayScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionsSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    matchIds: BigNumberish[],
    predictionsCount: BigNumberish,
    freeUsed: BigNumberish,
    feePaid: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    matchIds: bigint[],
    predictionsCount: bigint,
    freeUsed: bigint,
    feePaid: bigint
  ];
  export interface OutputObject {
    user: string;
    matchIds: bigint[];
    predictionsCount: bigint;
    freeUsed: bigint;
    feePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    matchId: BigNumberish,
    correct: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    matchId: bigint,
    correct: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    matchId: bigint;
    correct: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SeersLeagueV2 extends BaseContract {
  connect(runner?: ContractRunner | null): SeersLeagueV2;
  waitForDeployment(): Promise<this>;

  interface: SeersLeagueV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_MATCHES_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  PREDICTION_DEADLINE: TypedContractMethod<[], [bigint], "view">;

  PREDICTION_FEE: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FREE_PREDICTIONS: TypedContractMethod<[], [bigint], "view">;

  UPDATE_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  batchRecordResults: TypedContractMethod<
    [users: AddressLike[], matchIds: BigNumberish[], corrects: boolean[]],
    [void],
    "nonpayable"
  >;

  getContractInfo: TypedContractMethod<
    [],
    [
      [string, string, string, boolean, bigint] & {
        version: string;
        contractOwner: string;
        contractTreasury: string;
        isPaused: boolean;
        contractTotalMatches: bigint;
      }
    ],
    "view"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [SeersLeagueV2.MatchStructOutput],
    "view"
  >;

  getMatchStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        upcoming: bigint;
        finished: bigint;
        recorded: bigint;
      }
    ],
    "view"
  >;

  getUpcomingMatches: TypedContractMethod<
    [limit: BigNumberish],
    [[bigint[], bigint[]] & { matchIds: bigint[]; startTimes: bigint[] }],
    "view"
  >;

  getUserPrediction: TypedContractMethod<
    [user: AddressLike, matchId: BigNumberish],
    [SeersLeagueV2.PredictionStructOutput],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [SeersLeagueV2.UserStatsStructOutput],
    "view"
  >;

  lastLeaderboardUpdate: TypedContractMethod<[], [bigint], "view">;

  lastMatchUpdate: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        id: bigint;
        startTime: bigint;
        homeScore: bigint;
        awayScore: bigint;
        isRecorded: boolean;
        exists: boolean;
        recordedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  predictions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        matchId: bigint;
        outcome: bigint;
        timestamp: bigint;
        isProcessed: boolean;
      }
    ],
    "view"
  >;

  registerMatches: TypedContractMethod<
    [matchIds: BigNumberish[], startTimes: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  submitPredictions: TypedContractMethod<
    [matchIds: BigNumberish[], outcomes: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  totalMatches: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateLeaderboard: TypedContractMethod<[], [void], "nonpayable">;

  updateMatchResult: TypedContractMethod<
    [matchId: BigNumberish, homeScore: BigNumberish, awayScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPredictionHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        correctPredictions: bigint;
        totalPredictions: bigint;
        freePredictionsUsed: bigint;
        currentStreak: bigint;
        longestStreak: bigint;
        lastPredictionTime: bigint;
        totalFeesPaid: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_MATCHES_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREDICTION_DEADLINE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREDICTION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FREE_PREDICTIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPDATE_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchRecordResults"
  ): TypedContractMethod<
    [users: AddressLike[], matchIds: BigNumberish[], corrects: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, boolean, bigint] & {
        version: string;
        contractOwner: string;
        contractTreasury: string;
        isPaused: boolean;
        contractTotalMatches: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [SeersLeagueV2.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        upcoming: bigint;
        finished: bigint;
        recorded: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUpcomingMatches"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[bigint[], bigint[]] & { matchIds: bigint[]; startTimes: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPrediction"
  ): TypedContractMethod<
    [user: AddressLike, matchId: BigNumberish],
    [SeersLeagueV2.PredictionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [SeersLeagueV2.UserStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastLeaderboardUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastMatchUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        id: bigint;
        startTime: bigint;
        homeScore: bigint;
        awayScore: bigint;
        isRecorded: boolean;
        exists: boolean;
        recordedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        matchId: bigint;
        outcome: bigint;
        timestamp: bigint;
        isProcessed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerMatches"
  ): TypedContractMethod<
    [matchIds: BigNumberish[], startTimes: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitPredictions"
  ): TypedContractMethod<
    [matchIds: BigNumberish[], outcomes: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalMatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLeaderboard"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMatchResult"
  ): TypedContractMethod<
    [matchId: BigNumberish, homeScore: BigNumberish, awayScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userPredictionHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        correctPredictions: bigint;
        totalPredictions: bigint;
        freePredictionsUsed: bigint;
        currentStreak: bigint;
        longestStreak: bigint;
        lastPredictionTime: bigint;
        totalFeesPaid: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AutoMatchUpdate"
  ): TypedContractEvent<
    AutoMatchUpdateEvent.InputTuple,
    AutoMatchUpdateEvent.OutputTuple,
    AutoMatchUpdateEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchRegistered"
  ): TypedContractEvent<
    MatchRegisteredEvent.InputTuple,
    MatchRegisteredEvent.OutputTuple,
    MatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MatchResultUpdated"
  ): TypedContractEvent<
    MatchResultUpdatedEvent.InputTuple,
    MatchResultUpdatedEvent.OutputTuple,
    MatchResultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionsSubmitted"
  ): TypedContractEvent<
    PredictionsSubmittedEvent.InputTuple,
    PredictionsSubmittedEvent.OutputTuple,
    PredictionsSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ResultRecorded"
  ): TypedContractEvent<
    ResultRecordedEvent.InputTuple,
    ResultRecordedEvent.OutputTuple,
    ResultRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AutoMatchUpdate(uint256,uint256)": TypedContractEvent<
      AutoMatchUpdateEvent.InputTuple,
      AutoMatchUpdateEvent.OutputTuple,
      AutoMatchUpdateEvent.OutputObject
    >;
    AutoMatchUpdate: TypedContractEvent<
      AutoMatchUpdateEvent.InputTuple,
      AutoMatchUpdateEvent.OutputTuple,
      AutoMatchUpdateEvent.OutputObject
    >;

    "LeaderboardUpdated(uint256,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "MatchRegistered(uint256,uint256)": TypedContractEvent<
      MatchRegisteredEvent.InputTuple,
      MatchRegisteredEvent.OutputTuple,
      MatchRegisteredEvent.OutputObject
    >;
    MatchRegistered: TypedContractEvent<
      MatchRegisteredEvent.InputTuple,
      MatchRegisteredEvent.OutputTuple,
      MatchRegisteredEvent.OutputObject
    >;

    "MatchResultUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      MatchResultUpdatedEvent.InputTuple,
      MatchResultUpdatedEvent.OutputTuple,
      MatchResultUpdatedEvent.OutputObject
    >;
    MatchResultUpdated: TypedContractEvent<
      MatchResultUpdatedEvent.InputTuple,
      MatchResultUpdatedEvent.OutputTuple,
      MatchResultUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PredictionsSubmitted(address,uint256[],uint256,uint256,uint256)": TypedContractEvent<
      PredictionsSubmittedEvent.InputTuple,
      PredictionsSubmittedEvent.OutputTuple,
      PredictionsSubmittedEvent.OutputObject
    >;
    PredictionsSubmitted: TypedContractEvent<
      PredictionsSubmittedEvent.InputTuple,
      PredictionsSubmittedEvent.OutputTuple,
      PredictionsSubmittedEvent.OutputObject
    >;

    "ResultRecorded(address,uint256,bool,uint256)": TypedContractEvent<
      ResultRecordedEvent.InputTuple,
      ResultRecordedEvent.OutputTuple,
      ResultRecordedEvent.OutputObject
    >;
    ResultRecorded: TypedContractEvent<
      ResultRecordedEvent.InputTuple,
      ResultRecordedEvent.OutputTuple,
      ResultRecordedEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
