import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <div className="sticky top-0 z-50 w-full bg-black/95 backdrop-blur-xl border-b border-white/10">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex items-center gap-4">
            <Link 
              href="/"
              className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
              <span>Back to SeersLeague</span>
            </Link>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="prose prose-invert max-w-none">
          <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-gray-400 text-lg mb-8">Last Updated: October 23, 2025</p>

          <div className="space-y-8">
            {/* Introduction */}
            <section>
              <p className="text-gray-300 leading-relaxed">
                Welcome to SeersLeague ("SeersLeague," "we," "us," or "our"). These Terms of Service ("Terms") govern your access to and use of our Farcaster Mini App, associated website (league.seershub.com), and services (collectively, the "Service").
              </p>
              <p className="text-gray-300 leading-relaxed mt-4">
                By accessing, connecting your wallet to, or using the Service, you ("User," "you") agree to be bound by these Terms.
              </p>
            </section>

            {/* Section 1 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. The Service</h2>
              <p className="text-gray-300 leading-relaxed">
                SeersLeague is an on-chain, skill-based football (soccer) prediction application operating on the Base blockchain. The Service allows users to submit predictions on the outcomes (Home Win, Draw, or Away Win) of real-world football matches. Users compete based on the accuracy of their predictions. Top-performing users, as ranked on our leaderboard, may be eligible for rewards in USDC from a pool generated by participant entry fees.
              </p>
            </section>

            {/* Section 2 - Critical */}
            <section className="bg-red-900/20 border border-red-500/30 rounded-lg p-6">
              <h2 className="text-2xl font-semibold text-red-400 mb-4">
                2. CRITICAL: A Game of Skill, NOT G@mbling
              </h2>
              <p className="text-gray-300 leading-relaxed mb-4">
                This is the most important section of our Terms. By using the Service, you explicitly acknowledge and agree to the following:
              </p>
              
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-medium text-white mb-2">2.1. No G@mbling or B@tting</h3>
                  <p className="text-gray-300 leading-relaxed">
                    SeersLeague is NOT a g@mbling, b@tting, or wagering service. We do not offer odds, take "bets" on specific outcomes, or have any financial stake in the result of any match. The Service is strictly a peer-to-peer contest of skill.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">2.2. Purely Skill-Based</h3>
                  <p className="text-gray-300 leading-relaxed">
                    The Service is a game of skill. Success depends predominantly on the user's superior knowledge, experience, and expertise regarding football. Factors include analyzing team form, player statistics, injuries, historical performance, and other strategic factors. Outcomes are not based on random chance.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">2.3. No G@mbling License</h3>
                  <p className="text-gray-300 leading-relaxed">
                    Because the Service is structured as a skill-based contest and not a game of chance, it does not constitute g@mbling and operates without a g@mbling license.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">2.4. Prizes</h3>
                  <p className="text-gray-300 leading-relaxed">
                    All rewards (prizes) are determined by a user's proven skill and performance against other users in the contest. Rewards are distributed from a pool funded by the entry fees of all participants competing.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 3 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. Eligibility</h2>
              <p className="text-gray-300 leading-relaxed">
                You must be at least 18 years of age (or the age of legal majority in your jurisdiction) to use the Service. You are solely responsible for ensuring that your use of the Service is in full compliance with all laws, rules, and regulations applicable to you in your jurisdiction. The Service may not be available in all jurisdictions.
              </p>
            </section>

            {/* Section 4 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. Service Rules, Fees, and Rewards</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-medium text-white mb-2">4.1. Predictions</h3>
                  <p className="text-gray-300 leading-relaxed">
                    The Service displays real-world football matches sourced from third-party data providers (e.g., Football-data.org). We are not responsible for inaccuracies or delays in match data.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">4.2. Prediction Deadline (Security)</h3>
                  <p className="text-gray-300 leading-relaxed">
                    All predictions must be submitted and confirmed on-chain via our smart contract before the scheduled start time of the respective match. Our smart contract is designed to REJECT any prediction attempt submitted after a match has started. This mechanism is in place to prevent any form of "in-play" activity and ensure a fair, skill-based environment.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">4.3. Fees and Free Tier</h3>
                  <p className="text-gray-300 leading-relaxed">
                    Your first five (5) lifetime predictions on the Service are FREE. After your free predictions are used, a fixed entry fee (e.g., 0.50 USDC) is required for each subsequent prediction. This fee is payable in USDC on the Base Mainnet.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">4.4. Rewards Pool</h3>
                  <p className="text-gray-300 leading-relaxed">
                    A specified portion of the entry fees collected is allocated to a decentralized rewards pool. These rewards are distributed automatically by our smart contract to the most successful users based on the rules of the leaderboard and skill ranking.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 5 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. Wallet and On-Chain Security</h2>
              <p className="text-gray-300 leading-relaxed">
                To use the Service, you must connect a non-custodial blockchain wallet (e.g., via the Farcaster Mini App integration). You are solely responsible for the security of your wallet, private keys, and any associated credentials. SeersLeague has no control over your wallet, does not have access to your private keys, and is not responsible for any lost funds or unauthorized access to your wallet. All transactions (predictions, reward claims) are initiated and approved by you.
              </p>
            </section>

            {/* Section 6 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">6. User Conduct</h2>
              <p className="text-gray-300 leading-relaxed mb-4">You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                <li>Use the Service for any illegal activity.</li>
                <li>Attempt to cheat, exploit bugs, or manipulate the smart contract.</li>
                <li>Use automated scripts, bots, or other means to disrupt the Service or gain an unfair advantage.</li>
                <li>Falsify information or create multiple accounts to exploit the "Free Tier" promotion.</li>
              </ul>
            </section>

            {/* Section 7 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. Disclaimers and Limitation of Liability</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-medium text-white mb-2">7.1. "AS IS" Service</h3>
                  <p className="text-gray-300 leading-relaxed">
                    The Service is provided "AS IS" and "AS AVAILABLE" without any warranties.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">7.2. Blockchain Risks</h3>
                  <p className="text-gray-300 leading-relaxed">
                    You acknowledge the inherent risks of using blockchain technology, including network failures, high gas fees, transaction failures, and potential smart contract vulnerabilities. We are not liable for any losses incurred due to these risks.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-medium text-white mb-2">7.3. No Guarantee of Winnings</h3>
                  <p className="text-gray-300 leading-relaxed">
                    There is no guarantee that you will receive any rewards. Your performance is based entirely on your skill relative to other users.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 8 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. Termination</h2>
              <p className="text-gray-300 leading-relaxed">
                We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for any conduct that we believe violates these Terms or is harmful to other users or the Service.
              </p>
            </section>

            {/* Section 9 */}
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. Changes to These Terms</h2>
              <p className="text-gray-300 leading-relaxed">
                We may modify these Terms at any time. We will notify users of significant changes (e.g., via the app or our Farcaster channel). Your continued use of the Service after such changes constitutes your acceptance of the new Terms.
              </p>
            </section>
          </div>

          {/* Footer */}
          <div className="mt-12 pt-8 border-t border-gray-800">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
              <div>
                <p className="text-gray-400 text-sm">
                  © 2025 SeersLeague. All rights reserved.
                </p>
                <p className="text-gray-500 text-xs mt-1">
                  Built on Base blockchain • Powered by Farcaster
                </p>
              </div>
              <div className="flex gap-4">
                <Link 
                  href="/"
                  className="text-blue-400 hover:text-blue-300 text-sm transition-colors"
                >
                  Home
                </Link>
                <Link 
                  href="/leaderboard"
                  className="text-blue-400 hover:text-blue-300 text-sm transition-colors"
                >
                  Leaderboard
                </Link>
                <Link 
                  href="/profile"
                  className="text-blue-400 hover:text-blue-300 text-sm transition-colors"
                >
                  Profile
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

